# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o_4qG0JicvPJtZNs1BvgpaBLbX43YSJn
"""

pip install langchain_openai

import os
from google.colab import userdata

os.environ["GOOGLE_API_KEY"] = userdata.get("YOU_API_KEY")

!pip install -qU langchain-openai

pip install langchain_google_genai

import os
from google.colab import userdata




os.environ["LANGSMITH_API_KEY"] = userdata.get("LANGSMITH_API_KEY")
os.environ["GOOGLE_API_KEY"] = userdata.get("GOOGLE_API_KEY")




os.environ["LANGSMITH_TRACING"] = "true"
os.environ["LANGSMITH_PROJECT"] = "my-langchain-project"

from langchain_google_genai import ChatGoogleGenerativeAI


llm = ChatGoogleGenerativeAI(model="gemini-2.5-flash")


response = llm.invoke("Explain how LangSmith tracing works in one sentence.")
print(response.content)